auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: feimengspirit.com
url: http://www.feimengspirit.com
feed: /atom.xml
author_info: <a href="http://www.feimengspirit.com/">feimengspirit</a>
