auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: feimengspirit.com
url: http://feimengspirit.com
feed: /atom.xml
author_info: <a href="http://feimengspirit.com/">feimengspirit</a>
